### ISSUE TITLE
web interface installed not working

### ISSUE THREAD

**Issue by ManonGros** [genouest/biomaj-watcher#1]
Hi Biomaj team,

I wonder if you had this issue before:
I installed Biomaj3 on a centos 6.6 machine and it's working (I checked) and then I installed Biomaj-wtahcer and launched it (just changing the admin, port and globa_properties parameters in the production.ini file).
There is no apparent error messages and I can access to the web interface but when I click on the different buttons nothing happen (it seems like the interface is not linked with the background). Have you had any similar issue before? Do you have an idea of what could have gone wrong?

Thank you very much.

**Comment by osallou** [comment]
Hi, sorry for late response. No, I have not seen such error, but to debug several things can be done:
1) run biomaj-watcher in development mode (pserve  development.ini), you may see  internal errors due to wrong config etc... of course after settings correct parameters in development.ini.
2) in the browser, open the web developper tools and check at network messages. You should certainly see 404 or 500 HTTP errors).
